### ISSUE TITLE
Can't Flag Dissimilar Incident

### ISSUE THREAD

**Issue by smcgregor** [responsible-ai-collaborative/aiid#1318]
Console Error:

```
SimilarIncidents.js:81 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'filter')
    at SimilarIncidents.js:81:28
    at f (regeneratorRuntime.js:72:17)
    at Generator._invoke (regeneratorRuntime.js:55:24)
    at Generator.next (regeneratorRuntime.js:97:21)
    at n (asyncToGenerator.js:3:20)
    at o (asyncToGenerator.js:22:9)
    at asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at asyncToGenerator.js:19:12
    at Object.Ie (react-dom.production.min.js:54:317)
```

![Screen Shot 2022-10-25 at 9 51 23 PM](https://user-images.githubusercontent.com/64780/197937738-6417c2ec-6127-4bdd-b5bb-27c2ac0c80f2.png)

**Comment by smcgregor** [comment]
It just worked for me... I'll keep trying and re-open if it happens again.
