### ISSUE TITLE
GraphQL API endpoint throwing `500` 

### ISSUE THREAD

**Issue by kepae** [responsible-ai-collaborative/aiid#3106]
Reproducible on pages that require the API to load, such as submissions and risk checklists:
https://incidentdatabase.ai/apps/submitted/
https://incidentdatabase.ai/apps/checklists/

```
XHRPOST
https://incidentdatabase.ai/api/graphql
[HTTP/2 500  239ms]
```

Netlify functions UI indicates we have only used 30k of 150k requests. No other reported problems with netlify (https://www.netlifystatus.com/).

Found errors in the netlify logs UI. Repeated:

```Sep 18, 09:43:22 AM: b4838659 ERROR  Internal error occurred during request handling. Please check your implementation. Error: Error verifying user token!
Sep 18, 09:43:22 AM: b4838659 ERROR
Sep 18, 09:43:22 AM: b4838659 ERROR      at verifyToken (/var/task/.cache/functions/graphql.js:36783:11)
Sep 18, 09:43:22 AM: b4838659 ERROR      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Sep 18, 09:43:22 AM: b4838659 ERROR      at async getUserFromHeader (/var/task/.cache/functions/graphql.js:36801:18)
Sep 18, 09:43:22 AM: b4838659 ERROR      at async context (/var/task/.cache/functions/graphql.js:36817:18)
Sep 18, 09:43:22 AM: b4838659 ERROR      at async handler (/var/task/.cache/functions/graphql.js:37111:66)
Sep 18, 09:43:22 AM: b4838659 ERROR      at async requestListener (/var/task/.cache/functions/graphql.js:37357:34)
Sep 18, 09:43:22 AM: b4838659 Duration: 186.67 ms	Memory Usage: 189 MB	
```

**Comment by kepae** [comment]
Error originates at this line.
https://github.com/responsible-ai-collaborative/aiid/blob/0e0ef1b0dc48380dada558bdf598b64f4f557e6d/site/gatsby-site/server/context.ts#L51

**Comment by kepae** [comment]
This outage seems over and was caused by the upstream Mongo cloud auth resources we relied on for verifying users.
https://status.mongodb.com/incidents/1xm3z4xzcd4v
