### ISSUE TITLE
Not able to edit my own user first/last name

### ISSUE THREAD

**Issue by pdcp1** [responsible-ai-collaborative/aiid#3186]
I logged in in production using my user, but I'm not able to edit my first and last name.

### Step to reproduce
1. log in with a user with only `subscriber` role
2. go to "Account"
3. Click on "Edit"
4. Set first and last name and click "Submit"

### Notes
- User role: `subscriber`
- Error:
```
{
    "errors": [
        {
            "message": "not authorized",
            "path": [
                "updateOneUser"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "stacktrace": [
                    "Error: not authorized",
                    "    at Rule.func (/var/task/site/gatsby-site/netlify/functions/graphql.js:115903:12)",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async Rule.resolve (/var/task/site/gatsby-site/netlify/functions/graphql.js:114363:19)",
                    "    at async middleware2 (/var/task/site/gatsby-site/netlify/functions/graphql.js:114645:19)"
                ]
            }
        }
    ],
    "data": {
        "updateOneUser": null
    }
}
```

**Comment by pdcp1** [comment]
Closing this. It was already merged into Staging
